require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MASVirtualTryOnModuleExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ma-shop-virtual-try-on', :path => '../..'
end
